# alpha_sequences
# sequencias de aminoacidos da hemoglobina alpha 



# Human (Homo sapiens) [TaxId:  9606]2DN3:A|PDBID|CHAIN|SEQUENCE
seq_human = "VLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKY"

# Horse (Equus caballus) [TaxId:  9796]2D5X:A|PDBID|CHAIN|SEQUENCE
seq_horse = "VLSAADKTNVKAAWSKVGGHAGEYGAEALERMFLGFPTTKTYFPHFDLSHGSAQVKAHGKKVGDALTLAVGHLDDLPGALSNLSDLHAHKLRVDPVNFKLLSHCLLSTLAVHLPNDFTPAVHASLDKFLSSVSTVLTSKYR"

# Deer (Odocoileus virginianus) [TaxId:  9874]1HDS:A|PDBID|CHAIN|SEQUENCE
seq_deer = "VLSAANKSNVKAAWGKVGGNAPAYGAQALQRMFLSFPTTKTYFPHFDLSHGSAQQKAHGQKVANALTKAQGHLNDLPGTLSNLSNLHAHKLRVNPVNFKLLSHSLLVTLASHLPTNFTPAVHANLNKFLANDSTVLTSKYR"

# Cow (Bos taurus) [TaxId:  9913]2QSS:A|PDBID|CHAIN|SEQUENCE
seq_cow = "VLSAADKGNVKAAWGKVGGHAAEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGAKVAAALTKAVEHLDDLPGAL1SELSDLHAHKLRVDPVNFKLLSHSLLVTLASHLPSDFTPAVHASLDKFLANVSTVLTSKYR"

# Pig (Sus scrofa) [TaxId:  9823]1QPW:A|PDBID|CHAIN|SEQUENCE
seq_pig = "VLSAADKANVKAAWGKVGGQAGAHGAEALERMFLGFPTTKTYFPHFNLSHGSDQVKAHGQKVADALTKAVGHLDDLPGALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHHPDDFNPSVHASLDKFLANVSTVLTSKYR"

# Maned wolf (Chrysocyon brachyurus) [TaxId:  68728]1FHJ:A|PDBID|CHAIN|SEQUENCE
seq_wolf = "VLSPADKTNIKSTWDKIGGHAGDYGGEALDRTFQSFPTTKTYFPHFDLSPGSAQVKAHGKKVADALTTAVAHLDDLPGALSALSDLHAYKLRVDPVNFKLLSHCLLVTLACHHPTEFTPAVHASLDKFFTAVSTVLTSKYR"

# Chicken (Gallus gallus) [TaxId:  9031]1HBR:A|PDBID|CHAIN|SEQUENCE
seq_chicken = "MLTAEDKKLIQQAWEKAASHQEEFGAEALTRMFTTYPQTKTYFPHFDLSPGSDQVRGHGKKVLGALGNAVKNVDNLSQAMAELSNLHAYNLRVDPVNFKLLSQCIQVVLAVHMGKDYTPEVHAAFDKFLSAVSAVLAEKYR"

# Trout (Oncorhynchus mykiss) [TaxId:  8022]1OUT:A|PDBID|CHAIN|SEQUENCE
seq_trout = "XSLTAKDKSVVKAFWGKISGKADVVGAEALGRMLTAYPQTKTYFSHWADLSPGSGPVKKHGGIIMGAIGKAVGLMDDLVGGMSALSDLHAFKLRVDPGNFKILSHNILVTLAIHFPSDFTPEVHIAVDKFLAAVSAALADKYR"


# sequence list
seq_list = [seq_human, seq_horse, seq_deer, seq_cow, seq_pig, seq_wolf, seq_chicken, seq_trout]
